"""Counterfactual testing - swap generator + paired comparator.

See docs/17 for the concept and the Mode A (evaluator-bias) vs Mode B
(model-bias) distinction. This module is deliberately mode-agnostic:
it swaps text and compares paired score tables; WHAT the comparison
means depends on whether the twin's responses were re-generated by the
model (Mode B) or merely re-scored (Mode A).
"""

from __future__ import annotations

import re

import pandas as pd

# default gender term pairs - small and high-precision on purpose
# (see docs/17 for why we do not chase full English pronoun grammar)
DEFAULT_PAIRS = [
    ("he", "she"),
    # 'his' listed before 'him': a right-side 'her' resolves to 'his'
    # (attributive - "her mother" -> "his mother"), the common case in
    # our text; object-case 'met her' -> 'met his' is a known, accepted
    # imperfection (docs/17).
    ("his", "her"), ("him", "her"),
    ("man", "woman"), ("men", "women"),
    ("male", "female"), ("boy", "girl"),
    ("mr", "ms"), ("sir", "madam"),
    ("husband", "wife"), ("father", "mother"),
    ("son", "daughter"), ("brother", "sister"),
    ("gentleman", "lady"),
]

SWAPPABLE_TEXT_COLUMNS = ("request", "response", "context", "ground_truth")


def _match_case(source: str, replacement: str) -> str:
    """Give the replacement the source's capitalization shape."""
    if source.isupper():
        return replacement.upper()
    if source[:1].isupper():
        return replacement[:1].upper() + replacement[1:]
    return replacement


def swap_terms(text: str, pairs: list[tuple[str, str]] | None = None) -> str:
    """Swap each pair BOTH directions in one pass (sentinel technique so
    he->she does not immediately swap back), word-boundaried,
    case-preserving."""
    if not text:
        return text
    pairs = pairs or DEFAULT_PAIRS
    # phase 1: left-side terms -> unique sentinels
    for i, (a, b) in enumerate(pairs):
        text = re.sub(rf"\b{re.escape(a)}\b",
                      lambda m: f"\x00L{i}:{m.group(0)}\x00",
                      text, flags=re.IGNORECASE)
    # phase 2: right-side terms -> left-side replacements
    for i, (a, b) in enumerate(pairs):
        text = re.sub(rf"\b{re.escape(b)}\b",
                      lambda m, a=a: _match_case(m.group(0), a),
                      text, flags=re.IGNORECASE)
    # phase 3: sentinels -> right-side replacements
    def _resolve(m):
        i, original = int(m.group(1)), m.group(2)
        return _match_case(original, pairs[i][1])
    return re.sub("\x00L(\\d+):([^\x00]*)\x00", _resolve, text)


def generate_swapped(df: pd.DataFrame,
                     pairs: list[tuple[str, str]] | None = None,
                     text_columns: tuple[str, ...] = SWAPPABLE_TEXT_COLUMNS,
                     label_flips: dict[str, dict] | None = None) -> pd.DataFrame:
    """Build the demographic twin of a dataset.

    pairs: term pairs to swap in the text columns (default: gender set).
    label_flips: {column_name: {old: new, ...}} for segment metadata,
        default flips M/F in any column containing 'gender'.
    Row order and index are preserved - that pairing IS the method.
    """
    out = df.copy()
    for col in text_columns:
        if col in out.columns:
            out[col] = out[col].astype("string").fillna("").map(
                lambda t: swap_terms(t, pairs))
    if label_flips is None:
        label_flips = {}
        for col in out.columns:
            if "gender" in str(col).lower():
                label_flips[col] = {"M": "F", "F": "M",
                                    "Male": "Female", "Female": "Male"}
    for col, mapping in label_flips.items():
        if col in out.columns:
            out[col] = out[col].map(lambda v: mapping.get(v, v))
    return out


def counterfactual_compare(scores_a: pd.DataFrame, scores_b: pd.DataFrame,
                           score_cols: list[str],
                           label_a: str = "original",
                           label_b: str = "swapped") -> pd.DataFrame:
    """Paired comparison of two score tables (same rows, same order).

    Numeric columns -> mean values, mean paired difference, max |diff|.
    Boolean / categorical columns -> flip rate (share of rows whose
    value changed) plus the number of flips.
    """
    n = min(len(scores_a), len(scores_b))
    rows = []
    for col in score_cols:
        if col not in scores_a.columns or col not in scores_b.columns:
            continue
        # Free-text judge explanation columns (*_reason) are not verdicts:
        # they quote the swapped words, so they "change" on every row and
        # would report a meaningless ~100% flip rate. Exclude them.
        if str(col).endswith("_reason"):
            continue
        a = scores_a[col].iloc[:n].reset_index(drop=True)
        b = scores_b[col].iloc[:n].reset_index(drop=True)
        both = a.notna() & b.notna()
        if not both.any():
            continue
        a2, b2 = a[both], b[both]
        numeric = (pd.api.types.is_numeric_dtype(a2)
                   and not set(a2.unique()) <= {True, False, 0, 1})
        if numeric:
            diff = (b2.astype(float) - a2.astype(float))
            rows.append({"score column": col, "type": "numeric",
                         f"mean ({label_a})": round(float(a2.mean()), 4),
                         f"mean ({label_b})": round(float(b2.mean()), 4),
                         "mean paired diff": round(float(diff.mean()), 4),
                         "max |diff|": round(float(diff.abs().max()), 4),
                         "flips": None, "flip rate": None})
        else:
            flips = int((a2.astype(str) != b2.astype(str)).sum())
            rows.append({"score column": col, "type": "verdict",
                         f"mean ({label_a})": None, f"mean ({label_b})": None,
                         "mean paired diff": None, "max |diff|": None,
                         "flips": flips,
                         "flip rate": round(flips / len(a2), 4)})
    return pd.DataFrame(rows)


def row_diffs(df_a: pd.DataFrame, df_b: pd.DataFrame,
              columns: list[str], max_rows: int = 200) -> pd.DataFrame:
    """Side-by-side per-row view for the columns that changed."""
    n = min(len(df_a), len(df_b), max_rows)
    out = []
    for i in range(n):
        row = {"row": i}
        changed = False
        for col in columns:
            if col in df_a.columns and col in df_b.columns:
                va, vb = df_a[col].iloc[i], df_b[col].iloc[i]
                if str(va) != str(vb):
                    changed = True
                row[f"{col} (original)"] = va
                row[f"{col} (swapped)"] = vb
        if changed:
            out.append(row)
    return pd.DataFrame(out)
